	dc.b	54		; number of sequences is 54
	dc.b	'MONSTER HUNTER THEME'	; name of sequence 0
	dc.b	'ROACHES: LEVEL 1 STG 1'	; name of sequence 1
	dc.b	'GATOR LEVEL 1 STG 2'	; name of sequence 2
	dc.b	'RAT STG: LEVEL 1 STG 3'	; name of sequence 3
	dc.b	'SPIDER: LEVEL 1 STG 4'	; name of sequence 4
	dc.b	'HAND GRENADE'	; name of sequence 5
	dc.b	'HAND GUN'	; name of sequence 6
	dc.b	'HUMMING ROACH WINGS'	; name of sequence 7
	dc.b	'SAMPLED MACHINEGUNBURST'	; name of sequence 8
	dc.b	'SPLATTERING BLOOD'	; name of sequence 9
	dc.b	'POWER UP 1'	; name of sequence 10
	dc.b	'FLAME THROWER'	; name of sequence 11
	dc.b	'BIG EXPLODE SAMPLE'	; name of sequence 12
	dc.b	' LOSE THEME'	; name of sequence 13
	dc.b	'OCEAN LEVEL 3 STAGE 1'	; name of sequence 14
	dc.b	'POWER UP 2'	; name of sequence 15
	dc.b	'JUNGLE LEVEL 2 STAGE 1'	; name of sequence 16
	dc.b	'DINOSAUR LEVEL 2 STG 2'	; name of sequence 17
	dc.b	'T-REX LEVEL 2 STG 3'	; name of sequence 18
	dc.b	'BOND LEVEL 3 STG 2'	; name of sequence 19
	dc.b	'PIRATE LEVEL 3 STG 3'	; name of sequence 20
	dc.b	'SCRATCHING SAMPLE'	; name of sequence 21
	dc.b	'PTEODACTLE SCREAM SAMPL'	; name of sequence 22
	dc.b	'RUMBLE FOR TRIC SAMPLE'	; name of sequence 23
	dc.b	'T-REX SAMPLE'	; name of sequence 24
	dc.b	'MAN SCREAMING SAMPLE'	; name of sequence 25
	dc.b	'WAVES SOUND SAMPLE'	; name of sequence 26
	dc.b	'SUPER SONAR SAMPLE'	; name of sequence 27
	dc.b	'BONES COLAPSING SAMPLE'	; name of sequence 28
	dc.b	'NINJA SMOKE SAMPLE'	; name of sequence 29
	dc.b	'CLANK SAMPLE'	; name of sequence 30
	dc.b	'LION ROAR SAMPLE'	; name of sequence 31
	dc.b	'WHIP SAMPLE'	; name of sequence 32
	dc.b	'ALIEN SQUASH SAMPLE'	; name of sequence 33
	dc.b	'WHIRRING MACHINERY SMPL'	; name of sequence 34
	dc.b	'ELECTRICAL ZAP SAMPLE'	; name of sequence 35
	dc.b	'BIG METAL DOOR SAMPLE'	; name of sequence 36
	dc.b	'GLASS BREAKING SAMPLE'	; name of sequence 37
	dc.b	'BRAIN SPLURT SAMPLE'	; name of sequence 38
	dc.b	'DRIPPING SAMPLE LOOP'	; name of sequence 39
	dc.b	'ELEVATOR WHIRR SAMPLE'	; name of sequence 40
	dc.b	'BIG BELCH SAMPLE'	; name of sequence 41
	dc.b	'FINALE RUMBLE SAMPLE'	; name of sequence 42
	dc.b	'ORIENT LEVEL 4 STG 1'	; name of sequence 43
	dc.b	'RUSKIE LEVEL 4 STG 2'	; name of sequence 44
	dc.b	'NINJA LEVEL 4 STG 3'	; name of sequence 45
	dc.b	'2001 LEVEL 5 STG 1'	; name of sequence 46
	dc.b	'ROBATO LEVEL 5 STG 2'	; name of sequence 47
	dc.b	'TRNSFORMR LEVEL 5 STG 3'	; name of sequence 48
	dc.b	'SLIME LEVEL 6 STG 1'	; name of sequence 49
	dc.b	'WHIPIT LEVEL 6 STG 2'	; name of sequence 50
	dc.b	'BIZNESS LEVEL 6 STG 3'	; name of sequence 51
	dc.b	'BIG BOSS'	; name of sequence 52
	dc.b	'COMPLETE LEVEL SONG'	; name of sequence 53
