/*
	File:		S32.H

	Contains:	Include this file at the beginning of your program to
		get a 32 cell mode equate set.

	Written by:	Burt Sloane & Randel B. Reiss of Technopop

	Copyright:	c 1990 by Sega of America, Inc., all rights reserved.

	Change History:

	To Do:
*/

/* basic 32cell header file */

#include "memmapB.h"
#include "sprite.h"
#include "scroll.h"
#include "char.h"
#include "vdp.h"
#include "lib.h"

